# Przepisane z pseudokodu w poleceniu
    n = (30)
do
    for: k = 0..(n 1 -)
        block
            p = (1)
            k = (k 2 +)
        do {
            for: i = 0..(k 2 -)
                block
                    i = (i 2 +)
                do {
                    if: (k i %) = (0)
                        set: p = (0)
                }
            if: (p) = (1)
                print: k
        }